# Generated by Django 4.1.7 on 2023-05-02 14:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.FileField(default=None, max_length=250, null=True, upload_to='BusinessNews/')),
                ('news_heading', models.CharField(max_length=150)),
                ('news_subheading', models.CharField(max_length=400)),
                ('news_content', tinymce.models.HTMLField()),
                ('news_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PakistanNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.FileField(default=None, max_length=250, null=True, upload_to='PakistanNews/')),
                ('news_heading', models.CharField(max_length=150)),
                ('news_subheading', models.CharField(max_length=400)),
                ('news_content', tinymce.models.HTMLField()),
                ('news_city', models.CharField(max_length=50)),
                ('news_province', models.CharField(max_length=60)),
                ('news_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(default=None, max_length=250, null=True, upload_to='PhotoGallery/')),
                ('photo_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.FileField(default=None, max_length=250, null=True, upload_to='SportsNews/')),
                ('news_heading', models.CharField(max_length=150)),
                ('news_subheading', models.CharField(max_length=400)),
                ('news_content', tinymce.models.HTMLField()),
                ('news_category', models.CharField(max_length=50)),
                ('news_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.FileField(default=None, max_length=250, null=True, upload_to='TopNews/')),
                ('news_heading', models.CharField(max_length=150)),
                ('news_subheading', models.CharField(max_length=400)),
                ('news_content', tinymce.models.HTMLField()),
                ('news_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.FileField(default=None, max_length=250, null=True, upload_to='WorldNews/')),
                ('news_heading', models.CharField(max_length=150)),
                ('news_subheading', models.CharField(max_length=400)),
                ('news_content', tinymce.models.HTMLField()),
                ('news_country', models.CharField(max_length=100)),
                ('news_continent', models.CharField(max_length=60)),
                ('news_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
