# Generated by Django 4.1.7 on 2023-05-02 16:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_photo', models.FileField(default=None, max_length=250, null=True, upload_to='Opinion/')),
                ('opinion_heading', models.CharField(max_length=300)),
                ('opinion_content', tinymce.models.HTMLField()),
                ('writer', models.CharField(max_length=100)),
                ('writer_description', models.CharField(default=None, max_length=500)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
